name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20 x64
        uses: actions/setup-node@v4
        with:
          node-version: 20
          architecture: x64
          registry-url: 'https://registry.npmjs.org'
          scope: '@undp-data'

      - name: Publish
        run: |
          npm publish --access=public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
